### ISSUE TITLE
Error on line 36

### ISSUE THREAD

**Issue by lipim12** [llSourcell/pytorch_in_5_minutes#2]
For the line: print(t,loss.data[0])
I'm getting the following error while running the code on jupyter notebook
**"invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number"**

Any help?

**Comment by kesaroid** [comment]
Hey @lipim12 , change print(t,loss.data[0]) to print(t,loss.data).

The variable data isn't a list, hence the error.
